version: "2"

services:

    mysql:
        build:
          context: ./docker/mysql
          args:
            - MYSQL_VERSION=${MYSQL_VERSION}
        container_name: ${MYSQL_CONTAINER_NAME}
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
          - "${MYSQL_PORT}:3306"
        volumes:
          - ${MYSQLDATA_PATH_HOST}:/var/lib/mysql
          - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
          - /etc/localtime:/etc/localtime:ro 
        restart: always

    nginx:
        build:
          context: ./docker/nginx
        container_name: ${NGINX_CONTAINER_NAME}
        working_dir: ${APP_CODE_PATH_CONTAINER}
        ports:
         - "${NGINX_HOST_HTTP_PORT}:80"
         - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - /etc/localtime:/etc/localtime:ro 
        restart: always
      
    php-fpm:
        build: docker/php-fpm
        container_name: ${PHP_FPM_CONTAINER_NAME}   
        working_dir: ${APP_CODE_PATH_CONTAINER}
        volumes:
          - ./docker/php-fpm/php${PHP_VERSION}.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
          - /etc/localtime:/etc/localtime:ro 
        expose:
          - "9000"
        restart: always
    mongodb:
        build:
          context: ./docker/mongodb
        container_name: ${MONGODB_CONTAINER_NAME}
        restart: always
        volumes:
            - ${MONGODB_PATH_HOST}:/data/db
            - /etc/localtime:/etc/localtime:ro 
        ports:
            - "${MONGODB_PORT}:27017"

